#!/usr/bin/env python3
"""DELVE GDD-03 — procedural PBR texture sets for the yard prop materials.

Deterministic (seeded), seamless (periodic value noise), one script per
asset family per the production plan (doc 04). Textures are baked
T_*.png in assets/textures/, referenced from the Godot StandardMaterial3D
subresources in the scene (GLBs stay material-less).

Materials covered here (GDD-03 §6 texture table, all 1 K):
  T_YRD_BARREL_OAK   albedo/normal/roughness  barrels (A3)
  T_YRD_CRATE_PINE   albedo/normal/roughness  guard box / notice board wood
  T_YRD_METAL_BRONZE albedo/normal/roughness  lantern fittings (A4)
  T_YRD_PARCHMENT    albedo only              notice board sheet (A2)

The wall-era sets (T_YRD_STONE_WALL, T_YRD_WOOD_OAK_WORN,
T_YRD_METAL_IRON) were generated by the first iteration of this pipeline
and are committed as-is; `--regenerate-wall-sets` rebuilds them in the
same visual style (byte-different, visually equivalent).
"""
import argparse
import random
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]  # .godot/
OUT = ROOT / "assets" / "textures"
OUT.mkdir(parents=True, exist_ok=True)

SIZE = 1024


# ----------------------------------------------------------------- noise
def hash2(i: int, j: int, seed: int) -> float:
    """Deterministic lattice hash in [0, 1)."""
    h = (i * 374761393 + j * 668265263 + seed * 974634 + 0x9E3779B9) & 0xFFFFFFFF
    h = ((h ^ (h >> 13)) * 1274126177) & 0xFFFFFFFF
    return (h & 0xFFFFFF) / 0x1000000


def value_noise(x: float, y: float, period: int, seed: int) -> float:
    """Bilinear value noise, periodic with the given integer period."""
    xi, yi = int(x) % period, int(y) % period
    xf, yf = x - int(x), y - int(y)
    u = xf * xf * (3 - 2 * xf)
    v = yf * yf * (3 - 2 * yf)
    a = hash2(xi, yi, seed)
    b = hash2((xi + 1) % period, yi, seed)
    c = hash2(xi, (yi + 1) % period, seed)
    d = hash2((xi + 1) % period, (yi + 1) % period, seed)
    return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v


def fbm(x: float, y: float, period: int, seed: int,
        octaves: int = 5) -> float:
    total, amp, freq, norm = 0.0, 1.0, 1.0, 0.0
    for o in range(octaves):
        total += amp * value_noise(x * freq, y * freq,
                                   max(1, period // (2 ** o)), seed + o * 131)
        norm += amp
        amp *= 0.5
        freq *= 2
    return total / norm


def grid(fn) -> list:
    """Row-major [j][i] grid; fn(u, v) returns a pixel value or tuple."""
    return [[fn(i / SIZE, j / SIZE) for i in range(SIZE)] for j in range(SIZE)]


def gray_grid(fn) -> list:
    return [[(v, v, v) for v in row] for row in grid(fn)]


def normal_from(height: list, strength: float) -> list:
    """RGB normal map from a [0,1] height grid (central differences)."""
    out = []
    for j in range(SIZE):
        jm = (j - 1) % SIZE
        jp = (j + 1) % SIZE
        row = []
        for i in range(SIZE):
            im = (i - 1) % SIZE
            ip = (i + 1) % SIZE
            dx = (height[j][ip] - height[j][im]) * strength
            dy = (height[jp][i] - height[jm][i]) * strength
            l = (dx * dx + dy * dy + 1.0) ** 0.5
            row.append(((-dx / l * 0.5 + 0.5) * 255,
                        (-dy / l * 0.5 + 0.5) * 255,
                        (1.0 / l * 0.5 + 0.5) * 255))
        out.append(row)
    return out


def write_png(name: str, grid_data: list) -> None:
    img = Image.new("RGB", (SIZE, SIZE))
    img.putdata([(int(max(0, min(255, r))), int(max(0, min(255, g))),
                  int(max(0, min(255, b))))
                 for row in grid_data for r, g, b in row])
    path = OUT / f"{name}.png"
    img.save(path)
    print(f"{path.name}  ({SIZE}x{SIZE})")


# ------------------------------------------------------------- materials
def barrel_oak(seed: int = 41) -> None:
    """Vertical staves: 4 per tile (0.25 m each), grain + butt joints."""
    per = 4
    stave_tone = [0.90 + 0.2 * (hash2(k, 7, seed) - 0.5) for k in range(per)]

    def height(u, v):
        k = min(per - 1, int(u * per))
        fx = (u * per) - k
        crown = 1.0 - (2 * fx - 1) ** 2
        grain = fbm(u * 3.0, v * 22.0, 8, seed + k * 17, octaves=4)
        joint = max(0.0, 0.10 - abs(fx) / 0.06) \
            + max(0.0, 0.10 - abs(fx - 1.0) / 0.06)
        knot = max(0.0, 0.35 - abs(fbm(u * 6, v * 6, 6, seed + 991, 3) - 0.86) * 3)
        return 0.45 + 0.35 * crown + 0.25 * grain - 0.5 * joint - 0.4 * knot

    def albedo(u, v):
        k = min(per - 1, int(u * per))
        fx = (u * per) - k
        tone = stave_tone[k]
        grain = fbm(u * 3.0, v * 22.0, 8, seed + k * 17, octaves=4)
        joint = max(0.0, 0.25 - abs(fx) / 0.05) \
            + max(0.0, 0.25 - abs(fx - 1.0) / 0.05)
        knot = max(0.0, 0.5 - abs(fbm(u * 6, v * 6, 6, seed + 991, 3) - 0.86) * 3)
        m = 0.55 + 0.45 * grain - 0.7 * joint - 0.8 * knot
        return (146 * tone * m, 96 * tone * m, 48 * tone * m)

    def rough(u, v):
        k = min(per - 1, int(u * per))
        fx = (u * per) - k
        seam = max(0.0, 0.25 - abs(fx) / 0.05) + max(0.0, 0.25 - abs(fx - 1.0) / 0.05)
        return 95 + 90 * fbm(u, v, 4, seed + 5, 3) + 60 * seam

    h = grid(height)
    write_png("T_YRD_BARREL_OAK_albedo", grid(albedo))
    write_png("T_YRD_BARREL_OAK_normal", normal_from(h, 2.6))
    write_png("T_YRD_BARREL_OAK_roughness", gray_grid(rough))


def crate_pine(seed: int = 42) -> None:
    """Weathered plain pine: 4 horizontal planks per tile, knots, grain."""
    per = 4
    plank_tone = [0.88 + 0.24 * (hash2(k, 3, seed) - 0.5) for k in range(per)]

    def height(u, v):
        k = min(per - 1, int(v * per))
        fy = (v * per) - k
        seam = max(0.0, 0.12 - abs(fy) / 0.05) + max(0.0, 0.12 - abs(fy - 1.0) / 0.05)
        grain = fbm(u * 26.0, v * 3.0, 8, seed + k * 29, octaves=4)
        knot = max(0.0, 0.30 - abs(fbm(u * 5, v * 5, 5, seed + 173, 3) - 0.88) * 3)
        return 0.5 + 0.3 * grain - 0.5 * seam - 0.35 * knot

    def albedo(u, v):
        k = min(per - 1, int(v * per))
        fy = (v * per) - k
        tone = plank_tone[k]
        seam = max(0.0, 0.22 - abs(fy) / 0.04) + max(0.0, 0.22 - abs(fy - 1.0) / 0.04)
        grain = fbm(u * 26.0, v * 3.0, 8, seed + k * 29, octaves=4)
        knot = max(0.0, 0.45 - abs(fbm(u * 5, v * 5, 5, seed + 173, 3) - 0.88) * 3)
        m = 0.62 + 0.38 * grain - 0.6 * seam - 0.7 * knot
        return (168 * tone * m, 152 * tone * m, 120 * tone * m)  # grey-tan pine

    def rough(u, v):
        return 110 + 80 * fbm(u, v, 4, seed + 8, 3)

    h = grid(height)
    write_png("T_YRD_CRATE_PINE_albedo", grid(albedo))
    write_png("T_YRD_CRATE_PINE_normal", normal_from(h, 2.2))
    write_png("T_YRD_CRATE_PINE_roughness", gray_grid(rough))


def metal_bronze(seed: int = 43) -> None:
    """Dark worked bronze with mottled patina (no strong relief)."""

    def height(u, v):
        return 0.5 + 0.5 * fbm(u * 10.0, v * 10.0, 10, seed, 4)

    def albedo(u, v):
        mottle = fbm(u * 8.0, v * 8.0, 8, seed + 3, 4)
        patina = max(0.0, mottle - 0.62) / 0.38          # green spots
        wear = max(0.0, 0.42 - fbm(u * 20.0, v * 20.0, 20, seed + 7, 3))
        shine = 1.0 + 0.55 * wear
        r = (88 + (96 - 88) * patina) * shine
        g = (66 + (128 - 66) * patina) * shine
        b = (40 + (100 - 40) * patina) * shine
        return (r, g, b)

    def rough(u, v):
        wear = max(0.0, 0.42 - fbm(u * 20.0, v * 20.0, 20, seed + 7, 3))
        pat = max(0.0, fbm(u * 8.0, v * 8.0, 8, seed + 3, 4) - 0.62)
        return 150 - 70 * wear + 40 * pat

    h = grid(height)
    write_png("T_YRD_METAL_BRONZE_albedo", grid(albedo))
    write_png("T_YRD_METAL_BRONZE_normal", normal_from(h, 0.9))
    write_png("T_YRD_METAL_BRONZE_roughness", gray_grid(rough))


def parchment(seed: int = 44) -> None:
    """Aged paper with faint muster-notice writing and a wax seal."""
    rng = random.Random(seed)

    def albedo(u, v):
        blot = fbm(u * 6.0, v * 6.0, 6, seed, 4)
        edge = 1.0 - 0.18 * max(0.0, (max(u, v, 1 - u, 1 - v) - 0.82) / 0.18) ** 2
        m = 0.92 + 0.10 * blot
        return (225 * m * edge, 204 * m * edge, 158 * m * edge)

    img = Image.new("RGB", (SIZE, SIZE))
    img.putdata([(int(max(0, min(255, r))), int(max(0, min(255, g))),
                  int(max(0, min(255, b))))
                 for row in grid(albedo) for r, g, b in row])
    dr = ImageDraw.Draw(img)

    ink = (86, 66, 44)
    # title rule + heavier header dashes
    dr.rectangle([int(0.08 * SIZE), int(0.10 * SIZE), int(0.92 * SIZE),
                  int(0.115 * SIZE)], fill=(74, 55, 36))
    for _ in range(3):
        x0 = rng.uniform(0.10, 0.30)
        w = rng.uniform(0.25, 0.5)
        y = rng.uniform(0.145, 0.16)
        dr.rectangle([x0 * SIZE, y * SIZE, (x0 + w) * SIZE,
                      (y + 0.012) * SIZE], fill=ink)
    # body: rows of short dashes
    y = 0.22
    while y < 0.80:
        x = 0.10
        while x < 0.90:
            w = rng.uniform(0.035, 0.16)
            x += w
            if x + w < 0.90:
                dr.rectangle([x * SIZE, y * SIZE, (x + w) * SIZE,
                              (y + 0.008) * SIZE], fill=ink)
            x += rng.uniform(0.012, 0.03)
        y += rng.uniform(0.045, 0.06)
    # wax seal
    sx, sy, sr = 0.80 * SIZE, 0.86 * SIZE, 0.035 * SIZE
    dr.ellipse([sx - sr, sy - sr, sx + sr, sy + sr], fill=(138, 58, 40))
    dr.ellipse([sx - sr * 0.55, sy - sr * 0.55, sx + sr * 0.55,
                sy + sr * 0.55], fill=(104, 40, 28))
    img.save(OUT / "T_YRD_PARCHMENT_albedo.png")
    print(f"T_YRD_PARCHMENT_albedo.png  ({SIZE}x{SIZE})")


# ------------------------------------------------------------- wall sets
def wall_stone(seed: int = 21) -> None:
    """Coarse ashlar stone (rebuild of the committed set, same style)."""

    def height(u, v):
        per = 3  # 3 courses across the 4 m tile
        cy = (v * per) % 1
        k = int(v * per)
        cx = (u * (per * 2) + (0.5 if k % 2 else 0)) % 1
        joint = max(0.0, 0.06 - abs(cy)) + max(0.0, 0.045 - abs(cx))
        rough = fbm(u * 14.0, v * 14.0, 14, seed, 5)
        pitting = max(0.0, fbm(u * 30.0, v * 30.0, 30, seed + 11, 3) - 0.72)
        return 0.55 + 0.35 * rough - 1.2 * joint - 0.6 * pitting

    def albedo(u, v):
        g = 150 + 70 * fbm(u * 6, v * 6, 6, seed + 4, 4)
        return (g, g * 0.97, g * 0.90)

    def rough(u, v):
        return 160 + 60 * fbm(u * 8, v * 8, 8, seed + 9, 3)

    h = grid(height)
    for name, data in (("T_YRD_STONE_WALL_albedo", grid(albedo)),
                       ("T_YRD_STONE_WALL_normal", normal_from(h, 3.2)),
                       ("T_YRD_STONE_WALL_roughness", gray_grid(rough))):
        write_png(name, data)


def wood_oak_worn(seed: int = 22) -> None:
    """Worn oak planks, vertical (rebuild of the committed set, same
    style)."""

    def height(u, v):
        per = 2  # two 0.5 m planks across the 1 m tile
        k = int(u * per)
        fx = (u * per) % 1
        joint = max(0.0, 0.08 - abs(fx)) + max(0.0, 0.08 - abs(fx - 1.0))
        grain = fbm(u * 4.0, v * 26.0, 8, seed + k * 31, 5)
        wear = fbm(u * 8.0, v * 8.0, 8, seed + 77, 3)
        return 0.5 + 0.35 * grain - 1.0 * joint + 0.15 * wear

    def albedo(u, v):
        g = 140 + 60 * fbm(u * 4, v * 4, 4, seed + 2, 4)
        return (g, g * 0.62, g * 0.34)

    def rough(u, v):
        return 140 + 80 * fbm(u * 6, v * 6, 6, seed + 6, 3)

    h = grid(height)
    for name, data in (("T_YRD_WOOD_OAK_WORN_albedo", grid(albedo)),
                       ("T_YRD_WOOD_OAK_WORN_normal", normal_from(h, 2.8)),
                       ("T_YRD_WOOD_OAK_WORN_roughness", gray_grid(rough))):
        write_png(name, data)


def metal_iron(seed: int = 23) -> None:
    """Dark wrought iron (rebuild of the committed set, same style)."""

    def height(u, v):
        grain = fbm(u * 18.0, v * 6.0, 18, seed, 4)
        pitting = max(0.0, fbm(u * 40.0, v * 40.0, 40, seed + 5, 3) - 0.75)
        return 0.5 + 0.3 * grain - 0.5 * pitting

    def albedo(u, v):
        g = 48 + 34 * fbm(u * 12, v * 12, 12, seed + 1, 4)
        return (g, g * 1.05, g * 1.12)

    def rough(u, v):
        return 120 + 70 * fbm(u * 10, v * 10, 10, seed + 3, 3)

    h = grid(height)
    for name, data in (("T_YRD_METAL_IRON_albedo", grid(albedo)),
                       ("T_YRD_METAL_IRON_normal", normal_from(h, 1.4)),
                       ("T_YRD_METAL_IRON_roughness", gray_grid(rough))):
        write_png(name, data)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--regenerate-wall-sets", action="store_true",
                    help="also rebuild the committed wall-era sets "
                         "(byte-different, same visual style)")
    args = ap.parse_args()
    print("Generating prop texture sets (deterministic)...")
    barrel_oak()
    crate_pine()
    metal_bronze()
    parchment()
    if args.regenerate_wall_sets:
        print("Regenerating wall-era sets...")
        wall_stone()
        wood_oak_worn()
        metal_iron()
    print("TEX_DONE")
