extends Node
## Brand — the DELVE lockup geometry (GDD-07 §5.1).
##
## `data/brand.json` is generated by `tools/build_brand.py` alongside the brand
## PNGs, so the sting, the menu and the loading seal all light the emblem's
## steps from one source of truth instead of three copies of the same numbers.

const PATH := "res://data/brand.json"

var data: Dictionary = {}


func _ready() -> void:
	if not FileAccess.file_exists(PATH):
		push_warning("Brand: %s is missing; run tools/build_brand.py" % PATH)
		return
	var file := FileAccess.open(PATH, FileAccess.READ)
	var parsed: Variant = JSON.parse_string(file.get_as_text())
	if typeof(parsed) == TYPE_DICTIONARY:
		data = parsed


func emblem_size() -> Vector2:
	return _size("emblem", Vector2(24, 24))


func wordmark_size() -> Vector2:
	return _size("wordmark", Vector2(72, 22))


func lockup_size() -> Vector2:
	return _size("lockup", Vector2(96, 24))


func wordmark_cell_width() -> float:
	return float(data.get("wordmark", {}).get("cell_width", 14))


func wordmark_letters() -> PackedStringArray:
	return PackedStringArray(data.get("wordmark", {}).get("letters", ["D", "E", "L", "V", "E"]))


## The emblem's three descending steps as rects in emblem-local pixels. The
## boot sting lights them top to bottom; the loading seal lights them at
## 33 / 66 / 100 %.
func emblem_step_rects() -> Array[Rect2]:
	var out: Array[Rect2] = []
	for step in data.get("emblem", {}).get("steps", []):
		out.append(Rect2(
			float(step.get("x", 0)),
			float(step.get("y", 0)),
			float(step.get("w", 2)),
			float(step.get("h", 2))
		))
	return out


## Convenience: how many of the three steps should be lit at `progress` (0-1).
func lit_step_count(progress: float) -> int:
	var steps := emblem_step_rects().size()
	return clampi(int(ceil(clampf(progress, 0.0, 1.0) * steps)), 0, steps)


func _size(section: String, fallback: Vector2) -> Vector2:
	var size: Array = data.get(section, {}).get("size", [])
	if size.size() == 2:
		return Vector2(float(size[0]), float(size[1]))
	return fallback
