extends Node
## Palette — the locked colour ramp of the pixel build (GDD-06 §5.3).
##
## 32 "surface" colours (the warm surface world) and 8 "below" colours (the
## obelisk infection). The below ramp is never painted by hand: a LUT re-maps
## surface index -> below index at runtime, so the same art reads as infected
## without a second set of textures.
##
## Generated by `tools/build_palette.py`; `tests/test_palette.gd` and
## `tools/check_project.py` assert that this mirror never drifts from the PNG /
## JSON deliverables under `assets/pixel/palette/`.
##
## Usage: `Palette.ink`, `Palette.bronze`, `Palette.surface(12)`.

# Surface ramp, index order (ink, stone, parchment, bronze, oak, blood, moss,
# skin, dawn sky).
const SURFACE_HEX: PackedStringArray = PackedStringArray([
	# ink / shadow
	"#0A0C10", "#101418", "#1A2126", "#263038",
	# stone
	"#2C3238", "#474F55", "#6C757B", "#9AA3A8",
	# parchment
	"#B9A67F", "#D6C6A3", "#E9DFC8", "#F6EFDD",
	# bronze / gold
	"#5E3D19", "#8A5A26", "#B0793A", "#D9A463", "#F0CD8E",
	# oak / wood
	"#3F2410", "#5A3418", "#7A4B2A", "#A06A3C",
	# blood / rust
	"#5C1C17", "#8E2F26", "#B4553F",
	# moss / verge
	"#3C4823", "#5B6B34", "#7F8F4A",
	# skin
	"#8A5636", "#C08356", "#E8B58C",
	# dawn sky
	"#E0A06A", "#F2C98A",
])

# Below ramp (the infection), index order.
const BELOW_HEX: PackedStringArray = PackedStringArray([
	"#16343A", "#1C4F52", "#2F8F7A", "#74E0B4",
	"#2E2140", "#4B2E6B", "#8A4FD0", "#C9C2A8",
])

# Surface index -> below index (GDD-06 §5.3: stone<->teal, ink<->violet,
# parchment<->bone, bronze<->mint; the remaining families key by luminance).
const REMAP: PackedInt32Array = PackedInt32Array([
	4, 5, 5, 6,
	0, 1, 2, 2,
	7, 7, 7, 7,
	3, 3, 3, 3, 3,
	0, 1, 1, 2,
	4, 5, 6,
	0, 1, 2,
	7, 7, 7,
	1, 2,
])

## Named handles for the colours the shell draws with. `ui_kit.json` and the
## UI factory refer to these by name, never by hex.
var ink := Color("#101418")          ## ink-1: legal screen, card borders, text
var ink_0 := Color("#0A0C10")        ## ink-0: darkest keyline
var ink_2 := Color("#1A2126")        ## ink-2: raised ink panels
var stone_1 := Color("#474F55")      ## stone-1: disabled glyphs
var parchment := Color("#E9DFC8")    ## parchment-2: menu item face text
var parchment_1 := Color("#D6C6A3")  ## parchment-1: panel fill
var parchment_3 := Color("#F6EFDD")  ## parchment-3: panel highlight
var bronze := Color("#B0793A")       ## bronze-2: wordmark face, hover underline
var bronze_0 := Color("#5E3D19")     ## bronze-0: underline shadow
var bronze_3 := Color("#D9A463")     ## bronze-3: polish / practical glow
var blood := Color("#8E2F26")        ## blood-1: destructive confirms
var mint := Color("#74E0B4")         ## below-3: the mint accent (emblem pip)


func _ready() -> void:
	assert(SURFACE_HEX.size() == 32, "surface ramp must hold 32 colours")
	assert(BELOW_HEX.size() == 8, "below ramp must hold 8 colours")
	assert(REMAP.size() == SURFACE_HEX.size(), "REMAP must cover every surface colour")


## Surface colour by ramp index (0-31).
func surface(index: int) -> Color:
	return Color(SURFACE_HEX[index % SURFACE_HEX.size()])


## Below-ramp colour by index (0-7).
func below(index: int) -> Color:
	return Color(BELOW_HEX[index % BELOW_HEX.size()])


## The below-ramp colour a surface colour remaps to under infection.
func infected(index: int) -> Color:
	return below(REMAP[index % REMAP.size()])


## Blend between the surface colour and its infected twin (`infection` 0-1),
## which is what the zone LUT shader does on the GPU.
func blended(index: int, infection: float) -> Color:
	return surface(index).lerp(infected(index), clampf(infection, 0.0, 1.0))
